monitor_display:
  update_interval: 0.5
  trade_buffer_size: 30
  flow_bias_threshold_percent: 20
  volatility_high_threshold_pct: 0.5
  volatility_medium_threshold_pct: 0.2
  book_pressure_buy_threshold: 0.65
  book_pressure_sell_threshold: 0.35
  book_pressure_levels: 3
  recent_trades_display_count: 8
  divergence_alert_threshold_points: 2.0